export const CATEGORIES = {
  "question-paper": {
    keywords: [
      "question",
      "exam",
      "paper",
      "test",
      "marks",
      "answer",
      "write",
      "solve",
      "time",
      "allowed",
    ],
    keyPhrases: [
      "total marks",
      "time allowed",
      "answer all questions",
      "section a",
      "multiple choice",
    ],
  },
  notice: {
    keywords: [
      "notice",
      "feedback",
      "form",
      "competetion",
      "announcement",
      "attention",
      "inform",
      "regarding",
      "hereby",
      "issued",
    ],
    keyPhrases: [
      "public notice",
      "all concerned",
      "take notice that",
      "please note",
      "important notice",
    ],
  },
  notification: {
    keywords: [
      "notification",
      "circular",
      "official",
      "inform",
      "government",
      "authority",
      "directive",
    ],
    keyPhrases: [
      "government notification",
      "official notification",
      "it is notified",
      "circular no",
    ],
  },
  "score-card": {
    keywords: [
      "scorecard",
      "marksheet",
      "result",
      "grade",
      "score",
      "marks",
      "percentage",
      "cgpa",
      "semester",
    ],
    keyPhrases: [
      "marks obtained",
      "total score",
      "grade sheet",
      "examination result",
      "pass percentage",
    ],
  },
  certificate: {
    keywords: [
      "certificate",
      "certify",
      "achievement",
      "diploma",
      "degree",
      "awarded",
      "completion",
    ],
    keyPhrases: [
      "this is to certify",
      "has been awarded",
      "successfully completed",
      "date of issue",
    ],
  },
  invoice: {
    keywords: [
      "invoice",
      "bill",
      "payment",
      "amount",
      "total",
      "price",
      "tax",
      "due",
      "paid",
      "item",
    ],
    keyPhrases: [
      "invoice no",
      "billing address",
      "payment due",
      "total amount",
      "tax invoice",
    ],
  },
  "id-card": {
    keywords: [
      "id",
      "identity",
      "card",
      "passport",
      "aadhar",
      "pan",
      "identification",
      "number",
      "photo",
    ],
    keyPhrases: [
      "identity card",
      "date of birth",
      "identification number",
      "valid until",
      "authorized signature",
    ],
  },
  "medical-record": {
    keywords: [
      "medical",
      "surgical",
      "pathalogy",
      "lab",
      "laboratory",
      "prescription",
      "doctor",
      "patient",
      "medicine",
      "treatment",
      "diagnosis",
      "hospital",
    ],
    keyPhrases: [
      "patient name",
      "doctor's prescription",
      "medical history",
      "dosage",
      "follow up",
    ],
  },
  "bank-statement": {
    keywords: [
      "bank",
      "statement",
      "account",
      "balance",
      "transaction",
      "debit",
      "credit",
      "deposit",
      "withdrawal",
    ],
    keyPhrases: [
      "account statement",
      "opening balance",
      "closing balance",
      "transaction date",
      "statement period",
    ],
  },
  report: {
    keywords: [
      "report",
      "analysis",
      "findings",
      "summary",
      "conclusion",
      "recommendation",
      "research",
    ],
    keyPhrases: [
      "executive summary",
      "findings and analysis",
      "conclusion and recommendations",
      "reported by",
    ],
  },
  "admit-card": {
    keywords: [
      "admit",
      "card",
      "hall",
      "ticket",
      "examination",
      "venue",
      "candidate",
      "roll",
      "center",
    ],
    keyPhrases: [
      "hall ticket",
      "examination center",
      "admit card",
      "roll number",
      "reporting time",
    ],
  },
  "contract-agreement": {
    keywords: [
      "contract",
      "agreement",
      "parties",
      "terms",
      "conditions",
      "clause",
      "signed",
      "legal",
      "binding",
    ],
    keyPhrases: [
      "terms and conditions",
      "agreement between",
      "party of the first part",
      "hereinafter referred",
    ],
  },
  "salary-slip": {
    keywords: [
      "salary",
      "payslip",
      "pay",
      "earnings",
      "deductions",
      "net",
      "gross",
      "employee",
      "month",
    ],
    keyPhrases: [
      "salary slip",
      "pay period",
      "net pay",
      "gross earnings",
      "employee id",
    ],
  },
};
